school_management/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views

urlpatterns = [
    path('user/', include('user.urls')),
    path('school/', include('school.urls')),
    # path('details/',include('user.urls')),
    path("admin/", admin.site.urls),

]

# extra_patterns = [
#     path('user/', views.school_details),
#
# ]


#
# from user.views import View1
# urlpatterns = [
#     path('user/', View1.as_view()),
#     # path('user/', include('user.urls')),
# ]

user/urls.py
from django.urls import path
from . import views
from .views import UserDetail, Detail,AddUser
app_name = 'user'

urlpatterns = [
    # path('', views.index), #name='index'),
    path('', UserDetail.as_view()),
    path('<int:pk>/',Detail.as_view()),  #name='detail'),
    path('adduser/', AddUser.as_view(), name='adduser'),
    # path('', View1.as_view()),
    # path('<pk>', View2.as_view()),
    # path('<pk>/update', View3.as_view())
    # path('<pk>/delete',View4.as_view())
]


#
# from .views import View1,View2
# urlpatterns = [
#     path('', View1.as_view()),
#     path('<pk>',View2.as_view()),
# ]
# def test(id = None):
#     return id;
#
# print(test())

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
# from school.models import Standards
# from django.utils.translation import ugettext_lazy as _


FEMALE = "female"
MALE = "male"
GENDER = (
    (MALE, 'male'),
    (FEMALE, 'female')

)
STUDENT = "student"
FACULTY = "faculty"
PRINCIPAL = 'principal'

USER_CHOICES = ((STUDENT, 'student'), (FACULTY, 'faculty'), (PRINCIPAL, 'principal'))


class User(AbstractUser):
    """This model includes all the information related to user
      and user must be one"""
    mobile_number = models.CharField(max_length=10, help_text='phone_no should be added')
    birth_date = models.DateField(null=True, blank=True, help_text='birth date is stored')
    gender = models.CharField(choices=GENDER, blank=True, max_length=30)
    user_type = models.CharField(default=FACULTY, choices=USER_CHOICES, max_length=20)
    parent_name = models.CharField(help_text='enter student parent name', null=True, blank=True, max_length=50)

    def __str__(self):
        return f'{self.username}'

user/forms.py
from django import forms

from .models import User


class Adduser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'mobile_number','user_type','gender']

    def __init__(self, *args, **kwargs):
        super(Adduser, self).__init__(*args, **kwargs)
        # self.fields['user_type'] = 'student'
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

    def clean_username(self):
        username_check = self.cleaned_data['username']
        if username_check.isalpha() is False:
            raise forms.ValidationError('username not contain any number')
        return username_check

    def clean_last_name(self):
        # import pdb;pdb.set_trace()
        # cleaned_data = super().clean()
        # username_check = self.cleaned_data['username']
        firstname_check = self.cleaned_data['first_name']
        lastname_check = self.cleaned_data['last_name']
        # pass_check = cleaned_data['password']
        # type_check = cleaned_data['user_type']
        # number_check = cleaned_data['mobile_number']
        # # if username_check.isdigit() is False:
        # #     raise forms.ValidationError('username not contain any number')
        if firstname_check == lastname_check:
            # print('it worked') // to check weather things go in if condition or not.
            raise forms.ValidationError('Firstname and Last name cannot be same')
        return lastname_check

    def clean_password(self):
        pass_check = self.cleaned_data['password']
        if len(pass_check) > 8:
            raise forms.ValidationError('Password is not grater than 8 character')
        return pass_check

    def clean_mobile_number(self):
        number_check = self.cleaned_data['mobile_number']
        print(number_check.isnumeric())
        if len(number_check) < 10 or number_check.isnumeric() is False:
            raise forms.ValidationError('Enter a valid phone number')
        return number_check

    def clean_user_type(self):
        type_check = self.cleaned_data['user_type']
        if type_check != 'student':
            raise forms.ValidationError(f'Must select student type')
        return type_check

user/views.py
from django.http import HttpResponse
from .models import User
from django.shortcuts import render, get_object_or_404, redirect
from .forms import Adduser

from django.views.generic import ListView
from django.views.generic import DetailView, UpdateView, DeleteView,RedirectView,CreateView


class UserDetail(ListView):
    template_name = 'user/index.html'
    # queryset = User.objects.filter(id__lt=7)

    def get_queryset(self):
        # return User.objects.filter(id__lt=7)
        return User.objects.all().order_by('id')


class Detail(DetailView):
    template_name = 'user/detail.html'
    model = User


class AddUser(CreateView):
    template_name = 'user/adduser.html'
    form_class = Adduser
    success_url = '/user'

    def get(self, request, *args, **kwargs):
        data = {"user_type": "student"}
        form = Adduser(initial = data)
        # breakpoint()
        return render(request, 'user/adduser.html', {'form': form})

    def post(self, request, *args, **kwargs):
        data = {"user_type" :"student"}
        form = Adduser(request.POST, initial = data)
        # import pdb;pdb.set_trace()
        if form.is_valid():
            form.save()
        return render(request, 'user/adduser.html', {'form': form})
























#     def detail(request, user_id):
#     get_data = get_object_or_404(User, pk=user_id)
#     return render(request, 'user/detail.html', {'s1': get_data})


# class View1(ListView):
#     model = User
#     queryset = User.objects.filter(id__gt=5) #it wrote id which is grater than 5
#     # queryset = User.objects.filter(username__contains='he')
#
#
# class View2(DetailView):
#     model = User


# class View3(UpdateView):
#     model = User
#     fields = ['username']
#     success_url = "/"
#
#
# class View4(DeleteView):
#     model = User
#     success_url = "/"

#example of redirect method

def example(request):
    return redirect('/user/')

user/templates/user/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Form</title>
</head>
<style>
body
{
    background-color: #E5EBB2;
}
.one{

  width: 100px;
  height: 30px;
  border: 0;
  outline: none;
  background: #2b2d42;
  color: #fff;
  font-size: 22px;
  border-radius: 40px;
  text-align: center;
  box-shadow: 0 6px 20px -5px rgba(0, 0, 0, 0.4);
  overflow: hidden;
  cursor: pointer;
}

form{
    font-size: 19px;
    font-weight: bold;
    color: #33043D;
    padding-left: 20px;
}
h4{
    color: maroon;
}
h6{
    display: none
}
</style>
<body>
<!--<h1> hello today is {% now y %}</h1>-->
<!--<h2>time is {% now 'h'  %}</h2>-->
<!--<fieldset>-->

<!-- <form action = "" method = "post">-->
<!--     <h2><u> Student Form</u></h2>-->
<!--     <h4>{{ form.errors }}</h4>-->
<!--	{% csrf_token %}-->
<!--	{{ form.as_p }}-->


<!--</form>-->
<!--    </fieldset>-->
<!--{{ form.errors }}-->
<fieldset>
<form action="{% url 'user:adduser' %}" method="post">
    {% csrf_token %}
<br>
<h2><u> Student Form</u></h2>
User Name: {{ form.username }} <br>
    <h4>{{ form.username.errors }} </h4>
First Name: {{ form.first_name }}<br><br>
Last Name: {{ form.last_name }} <br>
   <h4>{{ form.last_name.errors }} </h4>
Email Address: {{form.email}} <br><br>
Password: {{form.password}} <br>
    <h4> {{ form.password.errors }} </h4>
Mobile Number: {{form.mobile_number}} <br><br>
  <h4>  {{ forms.mobile_number.errors }} </h4>
<h6>User Type: {{ form.user_type}} <br></h6>
    <h4>{{ forms.user_type.errors }} </h4>
Gender: {{ form.gender }} <br><br>
<input class="one" type="submit" value="submit">
</form>
</fieldset>
</body>
</html>

user/templates/user/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Management</title>
    <style>
        body{
            background-color: #faebf5;
        }
        h2{
            text-align: center;
        }
        td
        {
            padding: 15px;
        }
    </style>
</head>
<body>
    <fieldset>
        <h2>HIRAMNAI SCHOOL</h2>

    <h3><u> User Information </u></h3>
    <table border="1">

        <tr>
            <td>username</td>
            <td>user_type</td>
            <td>mobile number</td>
            <td>email address</td>
        </tr>
        <tr>
            <td> {{ object.username }} </td>
            <td> {{ object.user_type }}</td>
            <td> {{ object.mobile_number }} </td>
            <td> {{ object.email }} </td>
        </tr>

    </table>
<!--    <p>User name is <b> {{ s1.username }} </b>. User type is {{ s1.user_type }} {{ s1.first_name }}-->
<!--        {{ s1.last_name }} {{ s1.email_address }}</p>-->
    </fieldset>
<!--    <script>-->
<!--        prompt('java script run successfull')-->
<!--    </script>-->
</body>
</html>

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> UserList</title>
    <meta charset="UTF-8">

    <style>
        body {
            background-color: #ffe6e6;
        }
       li{
        font-family: "Times New Roman", Times, serif;
        font-size: 17px;
        color: black;
        position: none;
       }

    </style>
</head>
<body>
    <!--<h2>good evening </h2> -->
    <fieldset>
        <h4>- It is {% now "jS F Y H:i" %}</h4>
        <!--It is 21st November 2022 08:54 -->
    <h2>List of user</h2>
    {% for u in object_list %}
   <ul>
        <li> <a href="/user/{{u.id}}/">{{ u.id}} </a>, {{ u.username }} </li>
   </ul>
    {% endfor %}
<!--        <h1>{% comment %} hii there {% endcomment %}</h1>-->
<!--        {% lorem %} randomly shows paragraph-->
    </fieldset>
</body>
</html>

user/templates/user/user_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>

	<input type="submit" value="Confirm">
</form>

</body>
</html>

user/templates/user/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>{{ object.username  }}</h1>
  <p>{{ object.birth_date }}</p>
</body>
</html>

user/templates/user/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>
</body>
</html>

user/templates/user/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <ul>
	<!-- Iterate over object_list -->
	{% for object in object_list %}
	<!-- Display Objects -->
	  <li>{{ object.username }}</li>
	  <li>{{ object.user_type }}</li>


	<hr/>
	<!-- If object_list is empty -->
	{% empty %}
	<li>No objects yet.</li>
	{% endfor %}
</ul>

</body>
</html>