school/urls.py
from django.urls import path
from . import views
from .views import StandardDetail,SubjectDetail,AddSubject, AddStandard,UpdateStandard, Deletestandard,UpdateSubject,DeleteSubject,get_faculty
app_name = 'school'

urlpatterns = [
    path('', StandardDetail.as_view(), name='example1'),
    path('<pk>/update', UpdateStandard.as_view(), name='example'),
    path('<pk>/delete', Deletestandard.as_view()),
    # path('subject', views.subject_details),
    path('subject',SubjectDetail.as_view()),
    path('subject/<pk>/update', UpdateSubject.as_view()),
    path('subject/<pk>/delete', DeleteSubject.as_view()),
    path('addsubject', AddSubject.as_view()),
    path('addstandard', AddStandard.as_view()),
    path('login', views.Input1),
    path('base', views.get_faculty),

]

school_management/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views

urlpatterns = [
    path('user/', include('user.urls')),
    path('school/', include('school.urls')),
    # path('details/',include('user.urls')),
    path("admin/", admin.site.urls),

]

# extra_patterns = [
#     path('user/', views.school_details),
#
# ]


#
# from user.views import View1
# urlpatterns = [
#     path('user/', View1.as_view()),
#     # path('user/', include('user.urls')),
# ]

user/urls.py
from django.urls import path
from . import views
from .views import UserDetail, Detail,AddUser
app_name = 'user'

urlpatterns = [
    # path('', views.index), #name='index'),
    path('', UserDetail.as_view()),
    path('<int:pk>/',Detail.as_view()),  #name='detail'),
    path('adduser/', AddUser.as_view(), name='adduser'),
    # path('', View1.as_view()),
    # path('<pk>', View2.as_view()),
    # path('<pk>/update', View3.as_view())
    # path('<pk>/delete',View4.as_view())
]


#
# from .views import View1,View2
# urlpatterns = [
#     path('', View1.as_view()),
#     path('<pk>',View2.as_view()),
# ]
# def test(id = None):
#     return id;
#
# print(test())

school/models.py
from django.db import models

# Create your models here.
from django.db import models
from user.models import User
STANDARD_LIST = [
    ('std_5', 'STANDARD_5'),
    ('std_6', 'STANDARD_6'),
    ('std_7', 'STANDARD_7'),
    ('std_8', 'STANDARD_8'),
    ('std_9', 'STANDARD_9'),
    ('std_10', 'STANDARD_10'),
    ('std_11', 'STANDARD_11'),
    ('std_12', 'STANDARD_12'),
]
SUBJECT_LIST = [
    ('gujrati', 'Gujrati'),
    ('english', 'English'),
    ('maths', 'mathematics'),
    ('Science', 'science'),
    ('drawing', 'Drawing'),
    ('hindi', 'Hindi'),
    ('Social_science', 'Social_science'),
]

class SchoolDetails(models.Model):
    name = models.CharField(max_length=30, help_text='info_school name')
    address = models.TextField(help_text='info_school address')
    contact_number = models.CharField(max_length=10, help_text='school registered contact number')
    owner_name = models.CharField(max_length=20, help_text='info_school owner name')


class Standards(models.Model):
    name = models.CharField(max_length=30)
    # student = models.ForeignKey(User, help_text='list of student', on_delete=models.CASCADE, related_name='student',blank=True, null=True)
    class_teacher = models.ForeignKey(User, help_text='class teacher of standerd', blank=True, null=True, related_name='teacher', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class Subject(models.Model):
    sub_name = models.CharField(max_length=40, help_text='subject name to be stored')
    subject_teacher = models.ManyToManyField(User, help_text='each subject faculty name to be stored', related_name='subject')
    standards = models.ManyToManyField(Standards, help_text='every standard subject list to be stored', related_name='standard')

    def __str__(self):
        return f'{self.sub_name}'

        # stand = ",".join(str(stan) for stan in self.standards.all())
        # return "{},{}".format(self.sub_name, stand)
        # return f'{self.sub_name} ,{self.standards.all()}'
        # gujrati, < QuerySet[ < Standards: 9, pooja >] >
        #git working
        # standards = ", ".join(str(stan) for stan in self.standards.all())
        # return "{},{}".format(self.sub_name, standards)

school/forms.py
from django import forms

from .models import Subject, Standards


class Subject1(forms.ModelForm):
    class Meta:
        model = Subject
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(Subject1, self).__init__(*args, **kwargs)
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None


class Standard1(forms.ModelForm):
    # class_teacher = forms.ModelChoiceField(queryset=Standards.objects.filter(class_teacher__user_type='faculty'),empty_label=None)
    class Meta:
        model = Standards
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(Standard1, self).__init__(*args, **kwargs)
        # self.fields['class_teacher'].queryset = Standards.objects.filter(class_teacher__user_type='faculty')
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

    def clean(self):
        # import pdb;pdb.set_trace()
        # print('it worked')
        cleaned_data = super().clean()
        name_check = cleaned_data['name']
        if Standards.objects.filter(name=name_check).exists():
            # print('it worked') // to check weather things go in if condition or not.
            raise forms.ValidationError(f'Standard already registered.')
        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

school/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Subject, Standards
from .forms import Subject1, Standard1, LoginForm
from django.views.generic import DetailView, UpdateView, DeleteView,RedirectView, ListView, CreateView
# Create your views here.

def Input1(request):
    form_input = LoginForm()
    return render(request,'school/login.html', {'form': form_input})


def get_faculty(request):
    return render(request,'school/hello.html')


class StandardDetail(ListView):
    template_name = 'school/index.html'
    # def standard_details(request):
    queryset = Standards.objects.all().order_by('name')


class UpdateStandard(UpdateView):
    model = Standards
    fields = ['class_teacher']
    template_name = 'school/updatestand.html'
    success_url = "/school"
    # form_class = Standard1


class Deletestandard(DeleteView):
    model = Standards
    template_name = 'school/deletestand.html'
    success_url = "/school"


class SubjectDetail(ListView):
    template_name = 'school/subject.html'
    queryset = Subject.objects.all()


class UpdateSubject(UpdateView):
    model = Subject
    fields = ['subject_teacher', 'standards']
    template_name = 'school/updatesubject.html'
    success_url = "/school/subject"


class DeleteSubject(DeleteView):
    model = Subject
    template_name = 'school/deletesubject.html'
    success_url = "/school/subject"


class AddSubject(CreateView):
    # import pdb;pdb.set_trace()
    template_name = 'school/addsubject.html'
    form_class = Subject1

    def get(self, request, *args, **kwargs):
        form = Subject1()
        return render(request, 'school/addsubject.html', {'form': form})

    def post(self, request, *args, **kwargs):
        # import pdb;pdb.set_trace()
        form = Subject1(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = Subject1()
        return render(request, 'school/addsubject.html', {'form': form})


class AddStandard(CreateView):
    template_name = 'school/addstandards.html'
    form_class = Standard1

    def get(self, request, *args, **kwargs):
        add_stand = Standard1()
        return render(request, 'school/addstandards.html', {'add': add_stand})

    def post(self, request, *args, **kwargs):
    # import pdb; pdb.set_trace()
    #     if request.method == "POST":
        add_stand = Standard1(request.POST)
        if add_stand.is_valid():
            add_stand.save()
            add_stand = Standard1()
        # else:
        #     add_stand = Standard1()
        return render(request, 'school/addstandards.html', {'add': add_stand})

school/templates/school/addstandards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>addstandards</title>
</head>
<style>
    body{
    background-color:#F8EDE3;
    }
    .one{
    padding: 8px;
    background: #016ABC;
	color: #fff;
	border: 1px solid #eee;
	border-radius: 20px;
	box-shadow: 5px 5px 5px #eee;
	text-shadow: none;
    }
</style>
<body>
<fieldset>


    <h2>You can add standards here..</h2>
    <form action = "" method = "post">
	    {% csrf_token %}
	    {{add.as_p}}
<!--      {{ forms.first_name }}-->
        <input class="one" type="submit" value=Submit">
    </form>
    </fieldset>
</body>
</html>

school/templates/school/addsubject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body{
    background-color: #FEF9E7;
    }
    .one{
    padding: 8px;
    background: #016ABC;
	color: #fff;
	border: 1px solid #eee;
	border-radius: 20px;
	box-shadow: 5px 5px 5px #eee;
	text-shadow: none;
    }
</style>
<body>
<fieldset>
    <h2> You can add subjects here..</h2>
  <form action = "" method = "post">
	{% csrf_token %}
	{{form.as_p }}
<!--      {{ form.first_name }}-->

	<input class="one" type="submit" value="Submit">
</form>
</fieldset>
</body>
</html>

school/templates/school/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block title1 %} <h2>base html1</h2> {% endblock %}
</body>
</html>

school/templates/school/deletestand.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body{
        background-color: #FDEBD0;
    }
    form{
        font-size: 20px;
    }
</style>
<body>
    <form method="post">{% csrf_token %}
<p>Are you sure you want to delete standard "{{ object }}"?</p>
<br>
	<input type="submit" value="Confirm">
</form>

</body>
</html>

school/templates/school/deletesubject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body{
        background-color: #FDEBD0;
    }
    form{
        font-size: 20px;

    }
</style>
<body>
<form method="post">
    {% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>
<br>
	<input type="submit" value="Confirm">
</form>
</body>
</html>

school/templates/school/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>

<body>
{% extends 'school/base.html' %}
        {% block title1 %}
            <h3>Good Morning</h3>
        {% endblock %}
<h1>fdghdfg</h1>
</body>
</html>

school/templates/school/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Standards list</title>
</head>

<style>

    body{
     background-color: #F8EDE3;
    }
    a{
    font-size : 17px;
    color: black;
    padding: 6px;
    margin: 3px;
    margin-left:7px;
    text-decoration: none;
    border : 2px solid black;
    background: #E9F7EF;
    padding-top:2px;
    border-radius: 5px;

    }
    a:hover{
    color: #6E2C00;
    background-color: #D5DBDB ;
    }
    table{
    font-size : 18px;
    padding:15px;
    border-collapse: collapse;
    }
    td{
    padding:3px;
    padding-left: 10px;
    font-family: sans-serif;
    text-align: center;
    font-style: italic;
    border-radius:5px;
    }
    h4{
    padding-left: 23px;
    }
    .one{
    padding-left:27px;
    padding-right:27px;
    padding-top: 10px;
    padding-bottom: 10px;
    border-radius: 5px;
    }

</style>
<body>
   <fieldset>
    <h2><u>List of standards show below</u></h2>
       <br><br>
       <table border="1">
           <tr>
               <td>Standard Name</td>
               <td>Class Teacher</td>
               <td>Action</td>
               <td>Action</td>
           </tr>
             {% for u in object_list %}
           <tr>
               <td> {{u.name}} </td>
               <td>{{ u.class_teacher }}</td>
               <td class="one"><a href= "/school/{{ u.id }}/update" target="_blank">Edit</a></td>
<!--               <td class="one"><a href="{% url 'school:example' pk=u.id %} ">edit</a></td>-->
               <td class="one"><a href="/school/{{ u.id }}/delete" target="_blank">Delete</a></td>
           </tr>
            {% endfor %}
       </table>


<!--       {% for u in object_list %}-->
<!--    <ul>-->

<!--    <li> {{u.name}} ,{{ u.class_teacher }}-->


<!--    <a href="/school/{{ u.id }}/update" target="_blank">Edit</a>-->
<!--        <a href="/school/{{ u.id }}/delete" target="_blank">Delete</a>-->
<!--    </li>-->
<!--    </ul>-->
<!--       {% endfor %}-->
    </fieldset>
   <br>

<a class = "two" href="/school/addstandard" target="_blank">Add Standards</a>
<!--<a href="{% url 'school:example' 1 %}">click here</a>-->
</body>
</html>

school/templates/school/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
body{
    text-align: center;
    background-color: #F9EBEA;
}
form{
    font-size: 20px;
    padding-top: 200px;
}
</style>
<body>
<form action = "" method = "post">
	{% csrf_token %}
	    {{form.as_p }}
    <input type="button" value="login">
</form>
</body>
</html>

school/templates/school/subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subject list</title>
</head>
<style>

    body{
     background-color: #FEF9E7;

    }
    a{
    font-size : 17px;
    color: black;
    padding: 6px;
    margin: 3px;
    margin-left:7px;
    text-decoration: none;
    border : 2px solid black;
    background-color:  #D5F5E3;

    }
    table{
    font-size : 18px;
    padding: 15px;
    border-collapse: collapse;

    }
    td{
    padding:3px;
    padding-left: 10px;
    text-align: center;
    font-family: sans-serif;
    border-radius: 5px;
    }
    h4{
    padding-left: 23px;
    }
    .one{
    padding-left:27px;
    padding-right:27px;
    padding-top: 10px;
    padding-bottom:10px;
    border-radius: 5px;
    }
</style>
<body>
  <fieldset>
    <h2><u>List of subjects shown below</u></h2>
      <br><br>
      <table border ="1">
          <tr>
              <td>Subject Name</td>
              <td>Faculty Name</td>
              <td>Standards</td>
              <td>Action</td>
              <td>Action</td>
          </tr>
       {% for s1 in object_list %}

            {% for t in s1.subject_teacher.all %}

                {% for p in s1.standards.all %}
                <tr>
                    <td>{{ s1.sub_name }}</td>
                    <td>{{ t.username }} </td>
                    <td>{{ p.name }} </td>
                    <td class="one"><a href="/school/subject/{{ s1.id }}/update" target="_blank">Edit</a></td>
                    <td class="one"><a href="/school/subject/{{ s1.id }}/delete" target="_blank">Delete</a></td>
                </tr>
            {% endfor %}
            {% endfor %}
        {% endfor %}
      </table>
    </fieldset>
  <br>
<a href="/school/addsubject" target="_blank">Add Subject</a>
</body>
</html>

school/templates/school/updatestand.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body{
        background-color: #FDEBD0;
    }
    form{
        font-size: 20px;
    }
</style>
<body>
    <h1> You can update your data here...</h1>
    <h3>Note: You can only update class teacher</h3>
 <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
     <input type="submit" value="Save" autofocus></form>

</body>
</html>

school/templates/school/updatesubject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
     body{
        background-color: #FEF9E7;
    }
    form{
        font-size: 20px;
    }

</style>
<body>
<h2><u>You can update your data here...</u> </h2><br>
    <h3>Note: You can only update subject teacher and standards </h3>
 <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
     <input type="submit" value="Save" autofocus></form>
</body>
</html>